# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyjira < Formula
  desc "A minimal Jira CLI for the terminal inspired by lazygit"
  homepage "https://github.com/svenliebig/lazyjira"
  version "1.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/svenliebig/lazyjira/releases/download/v1.2.0/lazyjira_1.2.0_darwin_amd64.tar.gz"
      sha256 "1fb7ccf9eb938c604fc3c260ae3e23bd974d1096c15dbee0f78e2574631561da"

      def install
        bin.install "lazyjira"
      end
    end
    on_arm do
      url "https://github.com/svenliebig/lazyjira/releases/download/v1.2.0/lazyjira_1.2.0_darwin_arm64.tar.gz"
      sha256 "a4bd58ac1a5d5be0866994f7c1a777747a684882784a0bd513ecbb51bcf0ef04"

      def install
        bin.install "lazyjira"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/svenliebig/lazyjira/releases/download/v1.2.0/lazyjira_1.2.0_linux_amd64.tar.gz"
        sha256 "79fd520163cac0b97988361597e13c8717cb59dc116798b6840874d2f7c162e8"

        def install
          bin.install "lazyjira"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/svenliebig/lazyjira/releases/download/v1.2.0/lazyjira_1.2.0_linux_armv6.tar.gz"
        sha256 "8a90769518044783f24d44afb566f582353a8ef41e5a872c9f02105dbb011472"

        def install
          bin.install "lazyjira"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/svenliebig/lazyjira/releases/download/v1.2.0/lazyjira_1.2.0_linux_arm64.tar.gz"
        sha256 "2476c9b00d2b21fcfb6a8c5616a0880f1da19d46de7e9503196536734016a6a5"

        def install
          bin.install "lazyjira"
        end
      end
    end
  end
end
