# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyjira < Formula
  desc "A minimal Jira CLI for the terminal inspired by lazygit"
  homepage "https://github.com/svenliebig/lazyjira"
  version "1.5.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/svenliebig/lazyjira/releases/download/v1.5.0/lazyjira_1.5.0_darwin_amd64.tar.gz"
      sha256 "8194541bccbbadd7c4f12d0acecb4ad63577fc5a9f9a7d3982923bcc6a1b3ee2"

      def install
        bin.install "lazyjira"
      end
    end
    on_arm do
      url "https://github.com/svenliebig/lazyjira/releases/download/v1.5.0/lazyjira_1.5.0_darwin_arm64.tar.gz"
      sha256 "90f08b81adf511510a5c8df0756ebe03e8e84f20f3436c4a90bf16e69c8b1bef"

      def install
        bin.install "lazyjira"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/svenliebig/lazyjira/releases/download/v1.5.0/lazyjira_1.5.0_linux_amd64.tar.gz"
        sha256 "7cc5236d8b036f10255ee56f5563a254d6dbab14a964ef4b37c5272719758e59"

        def install
          bin.install "lazyjira"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/svenliebig/lazyjira/releases/download/v1.5.0/lazyjira_1.5.0_linux_armv6.tar.gz"
        sha256 "757ec87db50855ad4770a99e7c296be47818538e44e1d20cab568ae818ed161f"

        def install
          bin.install "lazyjira"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/svenliebig/lazyjira/releases/download/v1.5.0/lazyjira_1.5.0_linux_arm64.tar.gz"
        sha256 "7048167b5e94a51ede1df11d5fd28fb83114ce0b9830bf8f3feba5e9b1f42d80"

        def install
          bin.install "lazyjira"
        end
      end
    end
  end
end
