# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Phopy < Formula
  desc "A photo copy tool that organizes RAW and JPEG files"
  homepage "https://github.com/svenliebig/phopy"
  version "1.7.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/svenliebig/phopy/releases/download/v1.7.0/phopy_1.7.0_darwin_amd64.tar.gz"
      sha256 "48960137cf38096b04af76dde994842fdd37cd17d05fa7396df71770d84c33f9"

      def install
        bin.install "phopy"
      end
    end
    on_arm do
      url "https://github.com/svenliebig/phopy/releases/download/v1.7.0/phopy_1.7.0_darwin_arm64.tar.gz"
      sha256 "2001e098e1bfd47dd429380fc579debdc86e16d705931f66d13cb55c937cd251"

      def install
        bin.install "phopy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/svenliebig/phopy/releases/download/v1.7.0/phopy_1.7.0_linux_amd64.tar.gz"
        sha256 "bd71d3863d515686a4495a3458919aa65d09774fca8e43de5fa67d98b35982df"

        def install
          bin.install "phopy"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/svenliebig/phopy/releases/download/v1.7.0/phopy_1.7.0_linux_armv6.tar.gz"
        sha256 "e98fb3ab4254da3fe2fbde9c087ea44ad5cfb42a3db8fcb8cc208700f5a04a14"

        def install
          bin.install "phopy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/svenliebig/phopy/releases/download/v1.7.0/phopy_1.7.0_linux_arm64.tar.gz"
        sha256 "14b5f34e259c766a528b21b7296d0d136e445ac981f0a97b4b88a14cffdfc8e4"

        def install
          bin.install "phopy"
        end
      end
    end
  end
end
