# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Phopy < Formula
  desc "A photo copy tool that organizes RAW and JPEG files"
  homepage "https://github.com/svenliebig/phopy"
  version "1.6.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/svenliebig/phopy/releases/download/v1.6.1/phopy_1.6.1_darwin_amd64.tar.gz"
      sha256 "c73238c7e0509c39daf91eb7d5bbd8813f003c8ef88b24a747df7cd0e944b3ba"

      def install
        bin.install "phopy"
      end
    end
    on_arm do
      url "https://github.com/svenliebig/phopy/releases/download/v1.6.1/phopy_1.6.1_darwin_arm64.tar.gz"
      sha256 "8081fe79a6c16ca6c624842988b475701df7fdb8e8abf1560f64dd194409569b"

      def install
        bin.install "phopy"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/svenliebig/phopy/releases/download/v1.6.1/phopy_1.6.1_linux_amd64.tar.gz"
        sha256 "68821be2f29cedebfded7143ea90b619781616df0c0a3da325fa303939cfb362"

        def install
          bin.install "phopy"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/svenliebig/phopy/releases/download/v1.6.1/phopy_1.6.1_linux_armv6.tar.gz"
        sha256 "1de649d14419355ef6cf1902247305f8e049247573a7b1f47c1d4e3fa3a87a8a"

        def install
          bin.install "phopy"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/svenliebig/phopy/releases/download/v1.6.1/phopy_1.6.1_linux_arm64.tar.gz"
        sha256 "bfd61fe17fa0abe056f34761674f516112fbc75cba50413eda52414a5e9caa14"

        def install
          bin.install "phopy"
        end
      end
    end
  end
end
